version: '3.5'
services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped

  api:
    container_name: api_container
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "3000:8000"
    expose:
      - "3000"
    volumes:
      - ./api:/api
    networks:
      - postgres

  webapp:
    container_name: webapp_container
    build:
      context: webapp
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    expose:
      - "8080"
    volumes:
      - ./webapp:/webapp
      - /webapp/node_modules

  mailcatcher:
    container_name: mailcatcher_container
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"

  lavinmq:
    container_name: lavinmq_container
    image: cloudamqp/lavinmq
    ports:
      - "15672:15672"
      - "5672:5672"

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: